routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['namespace'=>'Backend', 'prefix' => 'admin' ,'middleware' => 'auth', 'as' => 'be.'], function () {

    //    Setting main
    Route::get('/','SettingSiteController@index')->name('settings');
    Route::post('/','SettingSiteController@update');

    // Route About
    Route::get('about','AboutController@index')->name('about');
    Route::post('about','AboutController@update');

    //    slider
    Route::group(['prefix' => 'slider'],function ()
    {
            Route::get('','SlidersController@index')->name('slide');
            Route::get('create','SlidersController@create')->name('slide.create');
            Route::post('create','SlidersController@store');
            Route::get('edit/{id}','SlidersController@edit')->name('slide.edit');
            Route::post('edit/{id}','SlidersController@update');
            Route::get('delte/{id}','SlidersController@destroy')->name('slide.delete');
    });
    //    artist
    Route::group(['prefix' => 'artist'],function (){
        Route::get('','ArtistsController@index')->name('artist');
        Route::get('create','ArtistsController@create')->name('artist.create');
        Route::post('create','ArtistsController@store');
        Route::get('edit/{id}','ArtistsController@edit')->name('artist.edit');
        Route::post('edit/{id}','ArtistsController@update');
        Route::get('delete/{id}','ArtistsController@destroy')->name('artist.delete');
    });
    //    albums
    Route::group(['prefix' => 'album'],function (){
        Route::get('','MusicAlbumController@index')->name('album');
        Route::get('create','MusicAlbumController@create')->name('album.create');
        Route::post('create','MusicAlbumController@store');
        Route::get('edit/{id}','MusicAlbumController@edit')->name('album.edit');
        Route::post('edit/{id}','MusicAlbumController@update');
        Route::get('delete/{id}','MusicAlbumController@destroy')->name('album.delete');
    });
    //Shop Categories
    Route::group(['prefix' => 'shopcategorie'],function (){
        Route::get('','ShopCategoriesController@index')->name('shopcategorie');
        Route::get('create','ShopCategoriesController@create')->name('shopcategorie.create');
        Route::post('create','ShopCategoriesController@store');
        Route::get('edit/{id}','ShopCategoriesController@edit')->name('shopcategorie.edit');
        Route::post('edit/{id}','ShopCategoriesController@update');
        Route::get('delete/{id}','ShopCategoriesController@destroy')->name('shopcategorie.delete');
    });
    //Service
    Route::group(['prefix' => 'service'],function (){
        Route::get('','ServicesController@index')->name('service');
        Route::get('create','ServicesController@create')->name('service.create');
        Route::post('create','ServicesController@store');
        Route::get('edit/{id}','ServicesController@edit')->name('service.edit');
        Route::post('edit/{id}','ServicesController@update');
        Route::get('delete/{id}','ServicesController@destroy')->name('service.delete');
    });

    //Shop
    Route::group(['prefix' => 'shop'],function (){
        Route::get('','ShopProductsController@index')->name('shop');
        Route::get('create','ShopProductsController@create')->name('shop.create');
        Route::post('create','ShopProductsController@store');
        Route::get('edit/{id}','ShopProductsController@edit')->name('shop.edit');
        Route::post('edit/{id}','ShopProductsController@update');
        Route::get('delete/{id}','ShopProductsController@destroy')->name('shop.delete');
    });

    //Song
    Route::group(['prefix' => 'song'],function (){
        Route::get('','SongListController@index')->name('song');
        Route::get('create','SongListController@create')->name('song.create');
        Route::post('create','SongListController@store');
        Route::get('edit/{id}','SongListController@edit')->name('song.edit');
        Route::post('edit/{id}','SongListController@update');
        Route::get('delete/{id}','SongListController@destroy')->name('song.delete');
    });

    Route::resource('chanel', 'MusicChanelController');
    //Shortlink
    Route::group(['prefix' => 'shortlink'],function (){
        Route::get('','ShortLinkController@index')->name('shortlink');
        Route::get('create','ShortLinkController@create')->name('shortlink.create');
        Route::post('create','ShortLinkController@store');
        Route::get('edit/{id}','ShortLinkController@edit')->name('shortlink.edit');
        Route::post('edit/{id}','ShortLinkController@update');
        Route::get('delete/{id}','ShortLinkController@destroy')->name('shortlink.delete');
    });

    //Shortlink
    Route::group(['prefix' => 'songs_received'],function (){
        Route::get('','SongReceivedController@index')->name('songs_received');
        Route::get('show/{id}','SongReceivedController@show')->name('song_show');

    });
    //Customer
    Route::group(['prefix' => 'customer'],function (){
        Route::get('send_mail','CustomerController@requestSendMail')->name('send_mail_cus');
        Route::post('send_mail','CustomerController@sendMail');
    });

});
Route::group(['namespace'=>'Frontend', 'middleware' => 'web'], function () {
    Route::get('',  'IndexController@services');
    Route::get('service', 'IndexController@services')->name('service');
    Route::get('event', 'IndexController@index')->name('home.index');
    Route::get('about', 'IndexController@about')->name('about');
    Route::get('shop', 'IndexController@shopProduct')->name('shopproduct');
    Route::get('shop/{slug}.html', 'IndexController@detailSong')->name('detailshop');
    Route::get('song', 'ListsongController@index')->name('listsong');
    Route::get('song/{slug}.html', 'ListsongController@detailSong')->name('detailsong');
    Route::get('artist', 'ArtistController@index')->name('artist');
    Route::get('artist/{slug}.html', 'ArtistController@detailArtist')->name('detailartist');
    Route::get('submission', 'MusicChanelController@index')->name('chanel');
    Route::get('submission/{slug}.html', 'SongReceivedController@index')->name('sendsong');
    Route::post('store-song', 'SongReceivedController@storeSong')->name('storesong');
    Route::get('customer', 'SongReceivedController@getCustomer')->name('getcustomer');
    Route::get('{code}', 'IndexController@shortLink')->name('home.shortlink');
});

resources/views/admin/albums/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Album nhạc</h1>
@stop

@section('content')
    <section class="content">

        <!-- SELECT2 EXAMPLE -->
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Thêm Album</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <form action="{{ route('be.album.create') }}" method="POST">
                        @csrf
                        @method('POST')
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tên Album</label>
                                <input class="form-control {{ $errors->has('title') ? 'has-error' : '' }}" name="title" value="{{ old('title') }}"> @if ($errors->has('title'))
                                    <span class="help-block">
                            <strong>{{ $errors->first('title') }}</strong>
                        </span> @endif
                            </div>

                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea id="my-editor" class="form-control {{ $errors->has('descriptions') ? 'has-error' : '' }}" name="descriptions">
                                {!! old('descriptions') !!}
                            </textarea>
                                @if ($errors->has('descriptions'))
                                    <span class="help-block">
                            <strong>{{ $errors->first('descriptions') }}</strong>
                            </span> @endif
                            </div>
                            <!-- /.form-group -->
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Image</label>
                                <div class="input-group">
                                <span class="input-group-btn">
                             <a id="lmfimage" data-input="images" class="btn btn-primary ">
                               <i class="fa fa-picture-o"></i> Choose
                             </a>
                           </span>
                                    <input id="images" class="form-control" value="{{ old('images') }}" type="text" name="images">
                                </div>
                                @if ($errors->has('images'))
                                    <span class="help-block">
                                     <strong>{{ $errors->first('images') }}</strong>
                                 </span> @endif
                            </div>
                            <div class="form-group">
                                <label>Multiple</label>
                                <select class="form-control select2" multiple="multiple" name="artist_id[]" data-placeholder="Chọn ca sỹ"
                                        style="width: 100%;">
                                   @foreach($artists as $artist)
                                       <option value="{{ $artist->id }}"> {{ $artist->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Tags SEO:</label>
                                <input class="form-control {{ $errors->has('tags') ? 'has-error' : '' }}" name="tags" value="{{ old('tags') }}"> @if ($errors->has('tags'))
                                    <span class="help-block">
                            <strong>{{ $errors->first('tags') }}</strong>
                        </span> @endif
                            </div>

                            <!-- /.form-group -->

                            <div class="form-group">
                                <button type="submit" name="submit" class="form-control btn btn-block btn-success">Lưu</button>
                                </span>

                            </div>
                            <!-- /.col -->
                            <!-- /.col -->
                        </div>

                    </form>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Visit <a href="https://select2.github.io/">Select2 documentation</a> for more examples and information about the plugin.
                </div>
            </div>
            <!-- /.box -->

    </section>
@stop
@section('js')
    <script>
        $('.select2').select2()
        $('#lmfimage').filemanager('image');
        CKEDITOR.replace('my-editor', options);
    </script>
@stop

resources/views/admin/albums/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Album</h1>
@stop

@section('content')
    <section class="content">

        <!-- SELECT2 EXAMPLE -->
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Sửa Album</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <form action="{{ route('be.album.edit',$album->id) }}" method="POST">
                        @csrf
                        @method('POST')
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Tên Album</label>
                                <input class="form-control {{ $errors->has('title') ? 'has-error' : '' }}" name="title" value="{{ old('title',$album->title) }}"> @if ($errors->has('title'))
                                    <span class="help-block">
                            <strong>{{ $errors->first('title') }}</strong>
                        </span> @endif
                            </div>

                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea id="my-editor" class="form-control {{ $errors->has('descriptions') ? 'has-error' : '' }}" name="descriptions">
                                {!! old('descriptions',$album->descriptions) !!}
                            </textarea>
                                @if ($errors->has('descriptions'))
                                    <span class="help-block">
                            <strong>{{ $errors->first('descriptions') }}</strong>
                            </span> @endif
                            </div>
                            <!-- /.form-group -->
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Image</label>
                                <div class="input-group">
                                <span class="input-group-btn">
                             <a id="lmfimage" data-input="images" class="btn btn-primary ">
                               <i class="fa fa-picture-o"></i> Choose
                             </a>
                           </span>
                                    <input id="images" class="form-control" value="{{ old('images',$album->images) }}" type="text" name="images">
                                </div>
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                     <strong>{{ $errors->first('title') }}</strong>
                                 </span> @endif
                            </div>
                            <div class="form-group">
                                <label>Multiple</label>
                                <select class="form-control select2" multiple="multiple" name="artist_id[]" data-placeholder="Chọn ca sỹ"
                                        style="width: 100%;">
                                    @foreach($artists as $artist)
                                        <option value="{{ $artist->id }}"
                                                @if(old('permission',in_array($artist->id,$album->artists()->pluck('id','id')->toArray()))) selected @endif>
                                            {{ $artist->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Tags SEO:</label>
                                <input class="form-control {{ $errors->has('tags') ? 'has-error' : '' }}" name="tags" value="{{ old('tags',$album->tags) }}"> @if ($errors->has('tags'))
                                    <span class="help-block">
                            <strong>{{ $errors->first('tags') }}</strong>
                        </span> @endif
                            </div>

                            <!-- /.form-group -->

                            <div class="form-group">
                                <button type="submit" name="submit" class="form-control btn btn-block btn-success">Lưu</button>
                                </span>

                            </div>
                            <!-- /.col -->
                            <!-- /.col -->
                        </div>

                    </form>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Visit <a href="https://select2.github.io/">Select2 documentation</a> for more examples and information about the plugin.
                </div>
            </div>
            <!-- /.box -->

    </section>
@stop
@section('js')
    <script>
        $('.select2').select2()
        $('#lmfimage').filemanager('image');
        CKEDITOR.replace('my-editor', options);
    </script>
@stop

resources/views/admin/albums/list.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Album</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <a class="btn btn-success" href="{{ route('be.album.create') }}"> Thêm</a>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="listdata" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>STT</th>
                            <th>Image</th>
                            <th>Tên(s)</th>
                            <th>Mô tả(s)</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($albums as $key => $item)
                            <tr>
                                <td>{{ $key+1 }}</td>
                                <td><img src="{{ $item->images }}" class="img-thumbnail" width="30px"></td>
                                <td>{{ $item->title }}</td>
                                <td>{!! $item->descriptions !!} </td>
                                <td>
                                    <a class="btn btn-success" href="{{ route('be.album.edit',$item->id) }}"> Sửa </a>
                                    <a class="btn btn-danger" href="{{ route('be.album.delete',$item->id) }}"> Xóa </a>
                                </td>

                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>STT</th>
                            <th>Image</th>
                            <th>Tên(s)</th>
                            <th>Mô tả(s)</th>
                            <th>Action</th>
                        </tr>
                        </tfoot>
                    </table>
                    {{ $albums->links() }}
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
@stop
@section('js')
    <script>
        $(function () {
            $('#listdata').DataTable({
                'paging': false,
                'lengthChange': false,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@stop