routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['namespace'=>'Backend', 'prefix' => 'admin' ,'middleware' => 'auth', 'as' => 'be.'], function () {

    //    Setting main
    Route::get('/','SettingSiteController@index')->name('settings');
    Route::post('/','SettingSiteController@update');

    // Route About
    Route::get('about','AboutController@index')->name('about');
    Route::post('about','AboutController@update');

    //    slider
    Route::group(['prefix' => 'slider'],function ()
    {
            Route::get('','SlidersController@index')->name('slide');
            Route::get('create','SlidersController@create')->name('slide.create');
            Route::post('create','SlidersController@store');
            Route::get('edit/{id}','SlidersController@edit')->name('slide.edit');
            Route::post('edit/{id}','SlidersController@update');
            Route::get('delte/{id}','SlidersController@destroy')->name('slide.delete');
    });
    //    artist
    Route::group(['prefix' => 'artist'],function (){
        Route::get('','ArtistsController@index')->name('artist');
        Route::get('create','ArtistsController@create')->name('artist.create');
        Route::post('create','ArtistsController@store');
        Route::get('edit/{id}','ArtistsController@edit')->name('artist.edit');
        Route::post('edit/{id}','ArtistsController@update');
        Route::get('delete/{id}','ArtistsController@destroy')->name('artist.delete');
    });
    //    albums
    Route::group(['prefix' => 'album'],function (){
        Route::get('','MusicAlbumController@index')->name('album');
        Route::get('create','MusicAlbumController@create')->name('album.create');
        Route::post('create','MusicAlbumController@store');
        Route::get('edit/{id}','MusicAlbumController@edit')->name('album.edit');
        Route::post('edit/{id}','MusicAlbumController@update');
        Route::get('delete/{id}','MusicAlbumController@destroy')->name('album.delete');
    });
    //Shop Categories
    Route::group(['prefix' => 'shopcategorie'],function (){
        Route::get('','ShopCategoriesController@index')->name('shopcategorie');
        Route::get('create','ShopCategoriesController@create')->name('shopcategorie.create');
        Route::post('create','ShopCategoriesController@store');
        Route::get('edit/{id}','ShopCategoriesController@edit')->name('shopcategorie.edit');
        Route::post('edit/{id}','ShopCategoriesController@update');
        Route::get('delete/{id}','ShopCategoriesController@destroy')->name('shopcategorie.delete');
    });
    //Service
    Route::group(['prefix' => 'service'],function (){
        Route::get('','ServicesController@index')->name('service');
        Route::get('create','ServicesController@create')->name('service.create');
        Route::post('create','ServicesController@store');
        Route::get('edit/{id}','ServicesController@edit')->name('service.edit');
        Route::post('edit/{id}','ServicesController@update');
        Route::get('delete/{id}','ServicesController@destroy')->name('service.delete');
    });

    //Shop
    Route::group(['prefix' => 'shop'],function (){
        Route::get('','ShopProductsController@index')->name('shop');
        Route::get('create','ShopProductsController@create')->name('shop.create');
        Route::post('create','ShopProductsController@store');
        Route::get('edit/{id}','ShopProductsController@edit')->name('shop.edit');
        Route::post('edit/{id}','ShopProductsController@update');
        Route::get('delete/{id}','ShopProductsController@destroy')->name('shop.delete');
    });

    //Song
    Route::group(['prefix' => 'song'],function (){
        Route::get('','SongListController@index')->name('song');
        Route::get('create','SongListController@create')->name('song.create');
        Route::post('create','SongListController@store');
        Route::get('edit/{id}','SongListController@edit')->name('song.edit');
        Route::post('edit/{id}','SongListController@update');
        Route::get('delete/{id}','SongListController@destroy')->name('song.delete');
    });

    Route::resource('chanel', 'MusicChanelController');
    //Shortlink
    Route::group(['prefix' => 'shortlink'],function (){
        Route::get('','ShortLinkController@index')->name('shortlink');
        Route::get('create','ShortLinkController@create')->name('shortlink.create');
        Route::post('create','ShortLinkController@store');
        Route::get('edit/{id}','ShortLinkController@edit')->name('shortlink.edit');
        Route::post('edit/{id}','ShortLinkController@update');
        Route::get('delete/{id}','ShortLinkController@destroy')->name('shortlink.delete');
    });

    //Shortlink
    Route::group(['prefix' => 'songs_received'],function (){
        Route::get('','SongReceivedController@index')->name('songs_received');
        Route::get('show/{id}','SongReceivedController@show')->name('song_show');

    });
    //Customer
    Route::group(['prefix' => 'customer'],function (){
        Route::get('send_mail','CustomerController@requestSendMail')->name('send_mail_cus');
        Route::post('send_mail','CustomerController@sendMail');
    });

});
Route::group(['namespace'=>'Frontend', 'middleware' => 'web'], function () {
    Route::get('',  'IndexController@services');
    Route::get('service', 'IndexController@services')->name('service');
    Route::get('event', 'IndexController@index')->name('home.index');
    Route::get('about', 'IndexController@about')->name('about');
    Route::get('shop', 'IndexController@shopProduct')->name('shopproduct');
    Route::get('shop/{slug}.html', 'IndexController@detailSong')->name('detailshop');
    Route::get('song', 'ListsongController@index')->name('listsong');
    Route::get('song/{slug}.html', 'ListsongController@detailSong')->name('detailsong');
    Route::get('artist', 'ArtistController@index')->name('artist');
    Route::get('artist/{slug}.html', 'ArtistController@detailArtist')->name('detailartist');
    Route::get('submission', 'MusicChanelController@index')->name('chanel');
    Route::get('submission/{slug}.html', 'SongReceivedController@index')->name('sendsong');
    Route::post('store-song', 'SongReceivedController@storeSong')->name('storesong');
    Route::get('customer', 'SongReceivedController@getCustomer')->name('getcustomer');
    Route::get('{code}', 'IndexController@shortLink')->name('home.shortlink');
});

resources/views/admin/about.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>About</h1>
@stop

@section('content')
    <section class="content">

        <!-- SELECT2 EXAMPLE -->
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Cài đặt About</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i>
                    </button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <form action="{{ route('be.about') }}" method="POST">
                        @csrf
                        @method('POST')
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Tiêu đề</label>
                                <input class="form-control {{ $errors->has('title') ? 'has-error' : '' }}" name="title"
                                       value="{{ old('title',$about->title) }}">
                                @if ($errors->has('title'))
                                    <span class="help-block">
                                     <strong>{{ $errors->first('title') }}</strong>
                                     </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea id="my-editor"
                                          class="form-control {{ $errors->has('contents') ? 'has-error' : '' }}"
                                          name="contents">
                                            {!!  old('contents',$about->contents)  !!}
                                 </textarea>
                                @if ($errors->has('contents'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('contents') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <button type="submit" name="submit" class="form-control btn btn-block btn-success">Lưu
                                </button>
                                </span>

                            </div>
                            <!-- /.col -->
                            <!-- /.col -->
                        </div>

                    </form>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                   Cài đặt giới thiệu về Dzusrecord
                </div>
            </div>
            <!-- /.box -->

    </section>
@stop

@section('js')
    <script>
        $('#lmflogo').filemanager('image');
        CKEDITOR.replace('my-editor', options);
    </script>
@stop

resources/views/admin/settingsite.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Cài đặt </h1>
@stop

@section('content')
    <section class="content">

        <!-- SELECT2 EXAMPLE -->
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Cài đặt</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <form action="{{ route('be.settings') }}" method="POST">
                        @csrf
                        @method('POST')
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Tiêu đề</label>
                            <input  class="form-control {{ $errors->has('title') ? 'has-error' : '' }}" name="title" value="{{ old('title',$settings->title) }}">
                            @if ($errors->has('title'))
                                <span class="help-block">
                            <strong>{{ $errors->first('title') }}</strong>
                        </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Map:</label>
                            <input  class="form-control {{ $errors->has('maps') ? 'has-error' : '' }}" name="maps" value="{{ old('maps',$settings->maps) }}">
                            @if ($errors->has('maps'))
                                <span class="help-block">
                            <strong>{{ $errors->first('maps') }}</strong>
                        </span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('descriptions') ? 'has-error' : '' }}">
                            <label>Mô tả</label>
                            <input  class="form-control"  name="descriptions" value="{{ old('descriptions',$settings->descriptions)  }}">
                            @if ($errors->has('descriptions'))
                                <span class="help-block">
                            <strong>{{ $errors->first('descriptions') }}</strong>
                        </span>
                            @endif
                        </div>
                         <div class="form-group  {{ $errors->has('spotify') ? 'has-error' : '' }}">
                            <label>Spotify</label>
                            <input  class="form-control" name="spotify" value="{{ old('spotify',$settings->spotify) }}">
                            @if ($errors->has('spotify'))
                                <span class="help-block">
                            <strong>{{ $errors->first('spotify') }}</strong>
                        </span>
                            @endif
                        </div>
                        <div class="form-group  {{ $errors->has('logo') ? 'has-error' : '' }}">
                            <label>Logo</label>
                            <div class="input-group">
                           <span class="input-group-btn">
                             <a data-input="logo" class="btn btn-primary lmflogo">
                               <i class="fa fa-picture-o"></i> Choose
                             </a>
                           </span>
                                <input id="logo" class="form-control"  value="{{ old('logo',$settings->logo) }}" type="text" name="logo">
                            </div>
                            @if ($errors->has('logo'))
                                <span class="help-block">
                                     <strong>{{ $errors->first('logo') }}</strong>
                                 </span>
                            @endif
                        </div>
                        <div class="form-group  {{ $errors->has('ogimage') ? 'has-error' : '' }}">
                            <label>OG image</label>
                            <div class="input-group">
                           <span class="input-group-btn">
                             <a data-input="ogimage" class="btn btn-primary lmflogo">
                               <i class="fa fa-picture-o"></i> Choose
                             </a>
                           </span>
                                <input id="ogimage" class="form-control"  value="{{ old('ogimage',$settings->ogimage) }}" type="text" name="ogimage">
                            </div>
                            @if ($errors->has('ogimage'))
                                <span class="help-block">
                                     <strong>{{ $errors->first('ogimage') }}</strong>
                                 </span>
                            @endif
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <div class="col-md-6">
                        <div class="form-group {{ $errors->has('tags') ? 'has-error' : '' }}">
                            <label>Tags SEO:</label>
                            <input  class="form-control" name="tags" value="{{ old('tags',$settings->tags) }}">
                            @if ($errors->has('tags'))
                                <span class="help-block">
                            <strong>{{ $errors->first('tags') }}</strong>
                        </span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('address') ? 'has-error' : '' }}">
                            <label>Địa chỉ:</label>
                            <input  class="form-control" name="address" value="{{ old('address',$settings->address) }}">
                            @if ($errors->has('address'))
                                <span class="help-block">
                            <strong>{{ $errors->first('address') }}</strong>
                        </span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('hotline') ? 'has-error' : '' }}">
                            <label>HOTLINE:</label>
                            <input  class="form-control" name="hotline" value="{{ old('hotline',$settings->hotline) }}">
                            @if ($errors->has('hotline'))
                                <span class="help-block">
                            <strong>{{ $errors->first('hotline') }}</strong>
                        </span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('facebook') ? 'has-error' : '' }}">
                            <label>Facebook:</label>
                            <input  class="form-control" name="facebook" value="{{ old('facebook',$settings->facebook) }}">
                            @if ($errors->has('facebook'))
                                <span class="help-block">
                            <strong>{{ $errors->first('facebook') }}</strong>
                        </span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('instargram') ? 'has-error' : '' }}">
                            <label>Instargram:</label>
                            <input  class="form-control" name="instargram" value="{{ old('instargram',$settings->instargram) }}">
                            @if ($errors->has('instargram'))
                                <span class="help-block">
                            <strong>{{ $errors->first('instargram') }}</strong>
                        </span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('youtube') ? 'has-error' : '' }}">
                            <label>Youtube:</label>
                            <input  class="form-control" name="youtube" value="{{ old('youtube',$settings->youtube) }}">
                            @if ($errors->has('youtube'))
                                <span class="help-block">
                            <strong>{{ $errors->first('youtube') }}</strong>
                        </span>
                            @endif
                        </div>
                        <!-- /.form-group -->

                        <div class="form-group">
                            <button type="submit" name="submit" class="form-control btn btn-block btn-success">Lưu</button>
                            </span>

                        </div>
                    <!-- /.col -->
                    <!-- /.col -->
                </div>

                </form>
                <!-- /.row -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                Visit <a href="https://select2.github.io/">Select2 documentation</a> for more examples and information about
                the plugin.
            </div>
        </div>
        <!-- /.box -->

    </section>
@stop

@section('js')
    <script>
        $('.lmflogo').filemanager('image');
        CKEDITOR.replace('my-editor', options);
    </script>
@stop